[theme]
base="dark"
font="Play:https://fonts.googleapis.com/css2?family=Play:wght@400;600;700&display=swap"
codeFont="https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;600;700&display=swap"